import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Withstore from "./WithStore";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bottom-left -z-10"></div>
        <div className="bottom-right -z-10"></div>
        <Withstore>{children}</Withstore>
      </body>
    </html>
  );
}
