import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Withstore from "./WithStore";
import { ReactNode } from "react";
import Footer from "@/components/footer";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-4 md:px-20`}
      >
        <div className="bottom-left -z-10"></div>
        <div className="bottom-right -z-10"></div>
        <Withstore>
          <Header />
          {children}
          <Footer />
        </Withstore>
      </body>
    </html>
  );
}
